version: '2'
services:
  mongodb:
    image: mongo:4.2
    container_name: grlog-mongo
    volumes:
      - mongo_data:/data/db

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: grlog-elasticsearch
    volumes:
      - es_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.2.0
    volumes:
       - graylog_data:/usr/share/graylog/data
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepassword
      - GRAYLOG_ROOT_PASSWORD_SHA2=somerootpassword
      # Login: admin
      # Password: someadminpassword
      - GRAYLOG_HTTP_EXTERNAL_URI=https://........./
      - GRAYLOG_HTTP_ENABLE_CORS=true
      - GRAYLOG_HTTP_ENABLE_GZIP=true
      - GRAYLOG_MESSAGE_JOURNAL_MAX_AGE=6h
      - GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE=4gb
      - GRAYLOG_RING_SIZE=65536
      - GRAYLOG_INBUFFER_RING_SIZE=65536
      - GRAYLOG_INBUFFER_PROCESSORS=2
      - GRAYLOG_PROCESSOR_WAIT_STRATEGY=sleeping
      - GRAYLOG_INBUFFER_WAIT_STRATEGY=sleeping
      - GRAYLOG_PROCESSBUFFER_PROCESSORS=2
      - GRAYLOG_INPUTBUFFER_PROCESSORS=2
      - GRAYLOG_OUTPUTBUFFER_PROCESSORS=2
      - GRAYLOG_ELASTICSEARCH_MAX_CONNECTIONS=1000
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - elasticsearch
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
  # logspout:
  #   image: gliderlabs/logspout:latest
  #   container_name: grlog-logspout
  #   restart: always
  #   volumes:
  #     - /etc/hostname:/etc/host_hostname:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command:
  #     multiline+syslog://graylog:1514

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local